#pragma once

#define ARUCOHEAD_MIN_VECTOR_SAMPLES 5
#define ARUCOHEAD_MAX_VECTOR_SAMPLES 20
#define ARUCOHEAD_LINE_THICKNESS_FRAME_SCALING_FACTOR (1.0/320.0)
#define ARUCOHEAD_MARKER_FLIP_DETECTION_THRESHOLD 120.0
#define ARUCOHEAD_MARKER_REPROJECTION_ERROR_THRESHOLD 0.2
#define ARUCOHEAD_MARKER_EXCLUSION_AMBIGUITY_THRESHOLD 0.9
#define ARUCOHEAD_ANGLE_COVERAGE_PITCH_STEPS 16
#define ARUCOHEAD_ANGLE_COVERAGE_YAW_STEPS 32
#define ARUCOHEAD_ANGLE_COVERAGE_VISIT_THRESHOLD 4
#define ARUCOHEAD_ROI_GROWTH_FACTOR 1.8